### ISSUE TITLE
Config Problem

### ISSUE THREAD

**Issue by shockwave82** [viyh/cbpi-brewfather#1]
Hi, I can't figure out how to configure the settings.
Is API_KEY the key I need to generate? Do I have to put all the long string that it generates and that is visible only once?
API_URL should I leave it as is or should I put the one with my ID, which appears under "custom flow"?

Thank you.

**Comment by viyh** [comment]
Hey there,

If you go to https://web.brewfather.app/tabs/settings, under the "Custom Stream" section, you will see a URL, something like https://log.brewfather.net/stream?id=aAbBcCdDeEfFgG. The URL is the https://log.brewfather.net/stream part (which is the default), and the API key is the part after "id=", "aAbBcCdDeEfFgG" in this example. Just set the key in your parameters and you should be good to go.
